name: MiKTeX

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install MiKTeX
      run:  bash .github/workflows/install-MiKTeX_hithesis.sh

    - name: Test doc
      run: |
        export PATH="/usr/local/bin:$PATH";
        make doc
    - name: Test chinese thesis
      run: |
        export PATH="/usr/local/bin:$PATH";
        CURRENTDIR=$(pwd)
        cd examples/hitbook/chinese
        make thesis
        cd $CURRENTDIR
    - name: Test english thesis
      run: |
        export PATH="/usr/local/bin:$PATH";
        CURRENTDIR=$(pwd)
        cd examples/hitbook/english
        make thesis
        cd $CURRENTDIR
    - name: Test reports
      run: |
        export PATH="/usr/local/bin:$PATH";
        CURRENTDIR=$(pwd)
        cd examples/hitart/reports
        make report
        cd $CURRENTDIR
    - name: Test reportplus
      run: |
        export PATH="/usr/local/bin:$PATH";
        CURRENTDIR=$(pwd)
        cd examples/hitart/reportplus
        make report
        cd $CURRENTDIR
